# Generated by Django 3.0.5 on 2020-04-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_event', models.CharField(max_length=10)),
                ('start_time', models.CharField(max_length=5)),
                ('end_time', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('num_volunteers_needed', models.IntegerField()),
                ('num_volunteers', models.IntegerField(default=0)),
            ],
        ),
    ]
