# Generated by Django 3.0.5 on 2020-04-15 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeping', '0002_auto_20200414_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='num_volunteers_needed',
            new_name='num_volunteers_total',
        ),
    ]
